[test]
onlyFailures = true
coverage = true
coverageReporter = ["text", "lcov"]
coverageThreshold = 0.9
coveragePathIgnorePatterns = [
  "node_modules/**",
  "dist/**",
  "src/transformers/luxon.transformer.ts",
  "src/transformers/moment.transformer.ts"
]

[test.reporter]
dots = true
